# SPDX-License-Identifier: GPL-2.0-only
obj-$(CONFIG_VFP)		+= vfp/
obj-$(CONFIG_XEN)		+= xen/
obj-$(CONFIG_VDSO)		+= vdso/
obj-y				+= kernel/ mm/ common/
obj-y				+= probes/
obj-y				+= net/
obj-y				+= crypto/

# for cleaning
subdir- += boot
